/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest;

import com.shell.apitest.authentication.MppTokenCredentials;
import com.shell.apitest.authentication.MppTokenModel;
import com.shell.apitest.authentication.OAuthTokenPostCredentials;
import com.shell.apitest.authentication.OAuthTokenPostModel;
import com.shell.apitest.http.client.ReadonlyHttpClientConfiguration;

/**
 * Configuration Interface for the library.
 */
public interface Configuration {

    /**
     * Current API environment.
     * @return a copy of environment
     */
    Environment getEnvironment();

    /**
     * Http Client Configuration instance.
     * @return a copy of httpClientConfig
     */
    ReadonlyHttpClientConfiguration getHttpClientConfig();

    /**
     * The timeout to use for making HTTP requests. The timeout to use for making HTTP requests.
     * @return a copy of timeout
     */
    long timeout();

    /**
     * The credentials to use with MppToken.
     * @return mppTokenCredentials
     */
    MppTokenCredentials getMppTokenCredentials();

    /**
     * The auth credential model for MppToken.
     * @return the instance of MppTokenModel
     */
    MppTokenModel getMppTokenModel();

    /**
     * The credentials to use with OAuthTokenPost.
     * @return oAuthTokenPostCredentials
     */
    OAuthTokenPostCredentials getOAuthTokenPostCredentials();

    /**
     * The auth credential model for OAuthTokenPost.
     * @return the instance of OAuthTokenPostModel
     */
    OAuthTokenPostModel getOAuthTokenPostModel();

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    String getBaseUri(Server server);

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    String getBaseUri();
}
