/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.authentication;

import io.apimatic.core.authentication.HeaderAuth;
import java.util.HashMap;

public class MppTokenManager extends HeaderAuth implements MppTokenCredentials {

    /**
     * Private instance of the auth model containing the auth credentials.
     */
    private MppTokenModel authModel;

    /**
     * Constructor that sets custom header parameters.
     */
    public MppTokenManager(MppTokenModel authModel) {

        super(new HashMap<String,String>() {
            private static final long serialVersionUID = 1L;
            {
                put("Authorization", authModel.getAuthorization());
            }
        });

        this.authModel = authModel;
    }

    /**
     * String value for authorization.
     * @return authorization
     */
    public String getAuthorization() {
        return authModel.getAuthorization();
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param authorization String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String authorization) {
        return authorization.equals(getAuthorization());
    }

    /**
     * Converts this MppTokenManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MppTokenManager [" + "authorization=" + getAuthorization() + "]";
    }
    /**
    * Returns the error message if the auth credentials are not valid.
    * @return the auth specific error message.
    */
    @Override
    public String getErrorMessage() {
        String errorMessage = super.getErrorMessage();
        if (errorMessage == null) {
            return null;
        }

        return "MppToken - " + errorMessage;
     }

}
