/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.authentication;

/**
 * A data class for Custom Header Signature credentials.
 */
public class MppTokenModel {
    private String authorization;

    /**
     * A Constructor for MppTokenModel.
     */
    private MppTokenModel(String authorization) {
        this.authorization = authorization;
    }

    /**
     * Getter for authorization.
     * @return authorization The value of Authorization.
     */
    public String getAuthorization() {
        return this.authorization;
    }

    /**
     * Builds a new {@link MppTokenModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link MppTokenModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getAuthorization());
    }

    /**
     * A Builder class for Custom Header Signature credentials.
     */
    public static class Builder {
        private String authorization;

        /**
         * The constructor with required auth credentials.
         * @param authorization The value of Authorization.
         */
        public Builder(String authorization) {
            if (authorization == null) {
                throw new NullPointerException("Authorization cannot be null.");
            }

            this.authorization = authorization;
        }

        /**
         * Setter for authorization.
         * @param authorization The value of Authorization.
         * @return Builder The current instance of Builder.
         */
        public Builder authorization(String authorization) {
            if (authorization == null) {
                throw new NullPointerException("Authorization cannot be null.");
            }

            this.authorization = authorization;
            return this;
        }

        /**
         * Builds the instance of MppTokenModel using the provided credentials.
         * @return The instance of MppTokenModel.
         */
        public MppTokenModel build() {
            return new MppTokenModel(authorization);
        }
    }
}