/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.authentication;

import io.apimatic.core.authentication.HeaderAuth;
import java.util.HashMap;

public class OAuthTokenPostManager extends HeaderAuth implements OAuthTokenPostCredentials {

    /**
     * Private instance of the auth model containing the auth credentials.
     */
    private OAuthTokenPostModel authModel;

    /**
     * Constructor that sets custom header parameters.
     */
    public OAuthTokenPostManager(OAuthTokenPostModel authModel) {

        super(new HashMap<String,String>() {
            private static final long serialVersionUID = 1L;
            {
                put("X-Apigee-Authorization", authModel.getXApigeeAuthorization());
            }
        });

        this.authModel = authModel;
    }

    /**
     * String value for xApigeeAuthorization.
     * @return xApigeeAuthorization
     */
    public String getXApigeeAuthorization() {
        return authModel.getXApigeeAuthorization();
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param xApigeeAuthorization String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String xApigeeAuthorization) {
        return xApigeeAuthorization.equals(getXApigeeAuthorization());
    }

    /**
     * Converts this OAuthTokenPostManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OAuthTokenPostManager [" + "xApigeeAuthorization=" + getXApigeeAuthorization()
                + "]";
    }
    /**
    * Returns the error message if the auth credentials are not valid.
    * @return the auth specific error message.
    */
    @Override
    public String getErrorMessage() {
        String errorMessage = super.getErrorMessage();
        if (errorMessage == null) {
            return null;
        }

        return "OAuthTokenPost - " + errorMessage;
     }

}
