/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.authentication;

/**
 * A data class for Custom Header Signature credentials.
 */
public class OAuthTokenPostModel {
    private String xApigeeAuthorization;

    /**
     * A Constructor for OAuthTokenPostModel.
     */
    private OAuthTokenPostModel(String xApigeeAuthorization) {
        this.xApigeeAuthorization = xApigeeAuthorization;
    }

    /**
     * Getter for xApigeeAuthorization.
     * @return xApigeeAuthorization The value of X-Apigee-Authorization.
     */
    public String getXApigeeAuthorization() {
        return this.xApigeeAuthorization;
    }

    /**
     * Builds a new {@link OAuthTokenPostModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link OAuthTokenPostModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getXApigeeAuthorization());
    }

    /**
     * A Builder class for Custom Header Signature credentials.
     */
    public static class Builder {
        private String xApigeeAuthorization;

        /**
         * The constructor with required auth credentials.
         * @param xApigeeAuthorization The value of XApigeeAuthorization.
         */
        public Builder(String xApigeeAuthorization) {
            if (xApigeeAuthorization == null) {
                throw new NullPointerException("XApigeeAuthorization cannot be null.");
            }

            this.xApigeeAuthorization = xApigeeAuthorization;
        }

        /**
         * Setter for xApigeeAuthorization.
         * @param xApigeeAuthorization The value of X-Apigee-Authorization.
         * @return Builder The current instance of Builder.
         */
        public Builder xApigeeAuthorization(String xApigeeAuthorization) {
            if (xApigeeAuthorization == null) {
                throw new NullPointerException("XApigeeAuthorization cannot be null.");
            }

            this.xApigeeAuthorization = xApigeeAuthorization;
            return this;
        }

        /**
         * Builds the instance of OAuthTokenPostModel using the provided credentials.
         * @return The instance of OAuthTokenPostModel.
         */
        public OAuthTokenPostModel build() {
            return new OAuthTokenPostModel(xApigeeAuthorization);
        }
    }
}