/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccessTokenResponse type.
 */
public class AccessTokenResponse {
    private String accessToken;
    private String expiresIn;
    private String tokenType;

    /**
     * Default constructor.
     */
    public AccessTokenResponse() {
        tokenType = "Bearer";
    }

    /**
     * Initialization constructor.
     * @param  accessToken  String value for accessToken.
     * @param  expiresIn  String value for expiresIn.
     * @param  tokenType  String value for tokenType.
     */
    public AccessTokenResponse(
            String accessToken,
            String expiresIn,
            String tokenType) {
        this.accessToken = accessToken;
        this.expiresIn = expiresIn;
        this.tokenType = tokenType;
    }

    /**
     * Getter for AccessToken.
     * It is the token used for the requests that required an authenticated user. This will be used
     * for all the callback URLs.
     * @return Returns the String
     */
    @JsonGetter("access_token")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * Setter for AccessToken.
     * It is the token used for the requests that required an authenticated user. This will be used
     * for all the callback URLs.
     * @param accessToken Value for String
     */
    @JsonSetter("access_token")
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * Getter for ExpiresIn.
     * validity of the access token in seconds
     * @return Returns the String
     */
    @JsonGetter("expires_in")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExpiresIn() {
        return expiresIn;
    }

    /**
     * Setter for ExpiresIn.
     * validity of the access token in seconds
     * @param expiresIn Value for String
     */
    @JsonSetter("expires_in")
    public void setExpiresIn(String expiresIn) {
        this.expiresIn = expiresIn;
    }

    /**
     * Getter for TokenType.
     * Type of token provided
     * @return Returns the String
     */
    @JsonGetter("token_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTokenType() {
        return tokenType;
    }

    /**
     * Setter for TokenType.
     * Type of token provided
     * @param tokenType Value for String
     */
    @JsonSetter("token_type")
    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    /**
     * Converts this AccessTokenResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccessTokenResponse [" + "accessToken=" + accessToken + ", expiresIn=" + expiresIn
                + ", tokenType=" + tokenType + "]";
    }

    /**
     * Builds a new {@link AccessTokenResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccessTokenResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accessToken(getAccessToken())
                .expiresIn(getExpiresIn())
                .tokenType(getTokenType());
        return builder;
    }

    /**
     * Class to build instances of {@link AccessTokenResponse}.
     */
    public static class Builder {
        private String accessToken;
        private String expiresIn;
        private String tokenType = "Bearer";



        /**
         * Setter for accessToken.
         * @param  accessToken  String value for accessToken.
         * @return Builder
         */
        public Builder accessToken(String accessToken) {
            this.accessToken = accessToken;
            return this;
        }

        /**
         * Setter for expiresIn.
         * @param  expiresIn  String value for expiresIn.
         * @return Builder
         */
        public Builder expiresIn(String expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        /**
         * Setter for tokenType.
         * @param  tokenType  String value for tokenType.
         * @return Builder
         */
        public Builder tokenType(String tokenType) {
            this.tokenType = tokenType;
            return this;
        }

        /**
         * Builds a new {@link AccessTokenResponse} object using the set fields.
         * @return {@link AccessTokenResponse}
         */
        public AccessTokenResponse build() {
            return new AccessTokenResponse(accessToken, expiresIn, tokenType);
        }
    }
}
