/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for AroundLocationArray type.
 */
public class AroundLocationArray {
    private List<AroundLocationArrayDataItems> data;

    /**
     * Default constructor.
     */
    public AroundLocationArray() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of AroundLocationArrayDataItems value for data.
     */
    public AroundLocationArray(
            List<AroundLocationArrayDataItems> data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * An array of station objects
     * @return Returns the List of AroundLocationArrayDataItems
     */
    @JsonGetter("data")
    public List<AroundLocationArrayDataItems> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * An array of station objects
     * @param data Value for List of AroundLocationArrayDataItems
     */
    @JsonSetter("data")
    public void setData(List<AroundLocationArrayDataItems> data) {
        this.data = data;
    }

    /**
     * Converts this AroundLocationArray into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AroundLocationArray [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link AroundLocationArray.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AroundLocationArray.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link AroundLocationArray}.
     */
    public static class Builder {
        private List<AroundLocationArrayDataItems> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of AroundLocationArrayDataItems value for data.
         */
        public Builder(List<AroundLocationArrayDataItems> data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  List of AroundLocationArrayDataItems value for data.
         * @return Builder
         */
        public Builder data(List<AroundLocationArrayDataItems> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link AroundLocationArray} object using the set fields.
         * @return {@link AroundLocationArray}
         */
        public AroundLocationArray build() {
            return new AroundLocationArray(data);
        }
    }
}
