/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CancelFuelingRequest type.
 */
public class CancelFuelingRequest {
    private String mppTransactionId;
    private String reasonCode;

    /**
     * Default constructor.
     */
    public CancelFuelingRequest() {
    }

    /**
     * Initialization constructor.
     * @param  mppTransactionId  String value for mppTransactionId.
     * @param  reasonCode  String value for reasonCode.
     */
    public CancelFuelingRequest(
            String mppTransactionId,
            String reasonCode) {
        this.mppTransactionId = mppTransactionId;
        this.reasonCode = reasonCode;
    }

    /**
     * Getter for MppTransactionId.
     * @return Returns the String
     */
    @JsonGetter("mppTransactionId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMppTransactionId() {
        return mppTransactionId;
    }

    /**
     * Setter for MppTransactionId.
     * @param mppTransactionId Value for String
     */
    @JsonSetter("mppTransactionId")
    public void setMppTransactionId(String mppTransactionId) {
        this.mppTransactionId = mppTransactionId;
    }

    /**
     * Getter for ReasonCode.
     * @return Returns the String
     */
    @JsonGetter("reasonCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Setter for ReasonCode.
     * @param reasonCode Value for String
     */
    @JsonSetter("reasonCode")
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }

    /**
     * Converts this CancelFuelingRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CancelFuelingRequest [" + "mppTransactionId=" + mppTransactionId + ", reasonCode="
                + reasonCode + "]";
    }

    /**
     * Builds a new {@link CancelFuelingRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CancelFuelingRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .mppTransactionId(getMppTransactionId())
                .reasonCode(getReasonCode());
        return builder;
    }

    /**
     * Class to build instances of {@link CancelFuelingRequest}.
     */
    public static class Builder {
        private String mppTransactionId;
        private String reasonCode;



        /**
         * Setter for mppTransactionId.
         * @param  mppTransactionId  String value for mppTransactionId.
         * @return Builder
         */
        public Builder mppTransactionId(String mppTransactionId) {
            this.mppTransactionId = mppTransactionId;
            return this;
        }

        /**
         * Setter for reasonCode.
         * @param  reasonCode  String value for reasonCode.
         * @return Builder
         */
        public Builder reasonCode(String reasonCode) {
            this.reasonCode = reasonCode;
            return this;
        }

        /**
         * Builds a new {@link CancelFuelingRequest} object using the set fields.
         * @return {@link CancelFuelingRequest}
         */
        public CancelFuelingRequest build() {
            return new CancelFuelingRequest(mppTransactionId, reasonCode);
        }
    }
}
