/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for CancelFuelingErrorResponse type.
 */
public class CancelFuelingErrorResponse {
    private String errorCode;
    private String errorDescription;
    private List<MppError> errors;

    /**
     * Default constructor.
     */
    public CancelFuelingErrorResponse() {
    }

    /**
     * Initialization constructor.
     * @param  errorCode  String value for errorCode.
     * @param  errorDescription  String value for errorDescription.
     * @param  errors  List of MppError value for errors.
     */
    public CancelFuelingErrorResponse(
            String errorCode,
            String errorDescription,
            List<MppError> errors) {
        this.errorCode = errorCode;
        this.errorDescription = errorDescription;
        this.errors = errors;
    }

    /**
     * Getter for ErrorCode.
     * The high level error code (e.g. missing data)
     * @return Returns the String
     */
    @JsonGetter("errorCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Setter for ErrorCode.
     * The high level error code (e.g. missing data)
     * @param errorCode Value for String
     */
    @JsonSetter("errorCode")
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * Getter for ErrorDescription.
     * The high level error message (e.g. mandatory fields have not been specified.
     * @return Returns the String
     */
    @JsonGetter("errorDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getErrorDescription() {
        return errorDescription;
    }

    /**
     * Setter for ErrorDescription.
     * The high level error message (e.g. mandatory fields have not been specified.
     * @param errorDescription Value for String
     */
    @JsonSetter("errorDescription")
    public void setErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
    }

    /**
     * Getter for Errors.
     * Array of error objects. Majority of the time the errorCode and errorDescription will suffice
     * @return Returns the List of MppError
     */
    @JsonGetter("errors")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<MppError> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * Array of error objects. Majority of the time the errorCode and errorDescription will suffice
     * @param errors Value for List of MppError
     */
    @JsonSetter("errors")
    public void setErrors(List<MppError> errors) {
        this.errors = errors;
    }

    /**
     * Converts this CancelFuelingErrorResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CancelFuelingErrorResponse [" + "errorCode=" + errorCode + ", errorDescription="
                + errorDescription + ", errors=" + errors + "]";
    }

    /**
     * Builds a new {@link CancelFuelingErrorResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CancelFuelingErrorResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .errorCode(getErrorCode())
                .errorDescription(getErrorDescription())
                .errors(getErrors());
        return builder;
    }

    /**
     * Class to build instances of {@link CancelFuelingErrorResponse}.
     */
    public static class Builder {
        private String errorCode;
        private String errorDescription;
        private List<MppError> errors;



        /**
         * Setter for errorCode.
         * @param  errorCode  String value for errorCode.
         * @return Builder
         */
        public Builder errorCode(String errorCode) {
            this.errorCode = errorCode;
            return this;
        }

        /**
         * Setter for errorDescription.
         * @param  errorDescription  String value for errorDescription.
         * @return Builder
         */
        public Builder errorDescription(String errorDescription) {
            this.errorDescription = errorDescription;
            return this;
        }

        /**
         * Setter for errors.
         * @param  errors  List of MppError value for errors.
         * @return Builder
         */
        public Builder errors(List<MppError> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Builds a new {@link CancelFuelingErrorResponse} object using the set fields.
         * @return {@link CancelFuelingErrorResponse}
         */
        public CancelFuelingErrorResponse build() {
            return new CancelFuelingErrorResponse(errorCode, errorDescription, errors);
        }
    }
}
