/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for FaultResponse type.
 */
public class FaultResponse {
    private FaultResponseFault fault;

    /**
     * Default constructor.
     */
    public FaultResponse() {
    }

    /**
     * Initialization constructor.
     * @param  fault  FaultResponseFault value for fault.
     */
    public FaultResponse(
            FaultResponseFault fault) {
        this.fault = fault;
    }

    /**
     * Getter for Fault.
     * @return Returns the FaultResponseFault
     */
    @JsonGetter("fault")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FaultResponseFault getFault() {
        return fault;
    }

    /**
     * Setter for Fault.
     * @param fault Value for FaultResponseFault
     */
    @JsonSetter("fault")
    public void setFault(FaultResponseFault fault) {
        this.fault = fault;
    }

    /**
     * Converts this FaultResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FaultResponse [" + "fault=" + fault + "]";
    }

    /**
     * Builds a new {@link FaultResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FaultResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .fault(getFault());
        return builder;
    }

    /**
     * Class to build instances of {@link FaultResponse}.
     */
    public static class Builder {
        private FaultResponseFault fault;



        /**
         * Setter for fault.
         * @param  fault  FaultResponseFault value for fault.
         * @return Builder
         */
        public Builder fault(FaultResponseFault fault) {
            this.fault = fault;
            return this;
        }

        /**
         * Builds a new {@link FaultResponse} object using the set fields.
         * @return {@link FaultResponse}
         */
        public FaultResponse build() {
            return new FaultResponse(fault);
        }
    }
}
