/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for FaultResponseFault type.
 */
public class FaultResponseFault {
    private String faultstring;
    private FaultResponseFaultDetail detail;

    /**
     * Default constructor.
     */
    public FaultResponseFault() {
    }

    /**
     * Initialization constructor.
     * @param  faultstring  String value for faultstring.
     * @param  detail  FaultResponseFaultDetail value for detail.
     */
    public FaultResponseFault(
            String faultstring,
            FaultResponseFaultDetail detail) {
        this.faultstring = faultstring;
        this.detail = detail;
    }

    /**
     * Getter for Faultstring.
     * The description of the error.
     * @return Returns the String
     */
    @JsonGetter("faultstring")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFaultstring() {
        return faultstring;
    }

    /**
     * Setter for Faultstring.
     * The description of the error.
     * @param faultstring Value for String
     */
    @JsonSetter("faultstring")
    public void setFaultstring(String faultstring) {
        this.faultstring = faultstring;
    }

    /**
     * Getter for Detail.
     * @return Returns the FaultResponseFaultDetail
     */
    @JsonGetter("detail")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FaultResponseFaultDetail getDetail() {
        return detail;
    }

    /**
     * Setter for Detail.
     * @param detail Value for FaultResponseFaultDetail
     */
    @JsonSetter("detail")
    public void setDetail(FaultResponseFaultDetail detail) {
        this.detail = detail;
    }

    /**
     * Converts this FaultResponseFault into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FaultResponseFault [" + "faultstring=" + faultstring + ", detail=" + detail + "]";
    }

    /**
     * Builds a new {@link FaultResponseFault.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FaultResponseFault.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .faultstring(getFaultstring())
                .detail(getDetail());
        return builder;
    }

    /**
     * Class to build instances of {@link FaultResponseFault}.
     */
    public static class Builder {
        private String faultstring;
        private FaultResponseFaultDetail detail;



        /**
         * Setter for faultstring.
         * @param  faultstring  String value for faultstring.
         * @return Builder
         */
        public Builder faultstring(String faultstring) {
            this.faultstring = faultstring;
            return this;
        }

        /**
         * Setter for detail.
         * @param  detail  FaultResponseFaultDetail value for detail.
         * @return Builder
         */
        public Builder detail(FaultResponseFaultDetail detail) {
            this.detail = detail;
            return this;
        }

        /**
         * Builds a new {@link FaultResponseFault} object using the set fields.
         * @return {@link FaultResponseFault}
         */
        public FaultResponseFault build() {
            return new FaultResponseFault(faultstring, detail);
        }
    }
}
