/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for FinaliseFuelingRequestPayment type.
 */
public class FinaliseFuelingRequestPayment {
    private String method;
    private String cardId;
    private String cardLastDigits;

    /**
     * Default constructor.
     */
    public FinaliseFuelingRequestPayment() {
    }

    /**
     * Initialization constructor.
     * @param  method  String value for method.
     * @param  cardId  String value for cardId.
     * @param  cardLastDigits  String value for cardLastDigits.
     */
    public FinaliseFuelingRequestPayment(
            String method,
            String cardId,
            String cardLastDigits) {
        this.method = method;
        this.cardId = cardId;
        this.cardLastDigits = cardLastDigits;
    }

    /**
     * Getter for Method.
     * @return Returns the String
     */
    @JsonGetter("method")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMethod() {
        return method;
    }

    /**
     * Setter for Method.
     * @param method Value for String
     */
    @JsonSetter("method")
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * Getter for CardId.
     * @return Returns the String
     */
    @JsonGetter("cardId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardId() {
        return cardId;
    }

    /**
     * Setter for CardId.
     * @param cardId Value for String
     */
    @JsonSetter("cardId")
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * Getter for CardLastDigits.
     * @return Returns the String
     */
    @JsonGetter("cardLastDigits")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardLastDigits() {
        return cardLastDigits;
    }

    /**
     * Setter for CardLastDigits.
     * @param cardLastDigits Value for String
     */
    @JsonSetter("cardLastDigits")
    public void setCardLastDigits(String cardLastDigits) {
        this.cardLastDigits = cardLastDigits;
    }

    /**
     * Converts this FinaliseFuelingRequestPayment into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FinaliseFuelingRequestPayment [" + "method=" + method + ", cardId=" + cardId
                + ", cardLastDigits=" + cardLastDigits + "]";
    }

    /**
     * Builds a new {@link FinaliseFuelingRequestPayment.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FinaliseFuelingRequestPayment.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .method(getMethod())
                .cardId(getCardId())
                .cardLastDigits(getCardLastDigits());
        return builder;
    }

    /**
     * Class to build instances of {@link FinaliseFuelingRequestPayment}.
     */
    public static class Builder {
        private String method;
        private String cardId;
        private String cardLastDigits;



        /**
         * Setter for method.
         * @param  method  String value for method.
         * @return Builder
         */
        public Builder method(String method) {
            this.method = method;
            return this;
        }

        /**
         * Setter for cardId.
         * @param  cardId  String value for cardId.
         * @return Builder
         */
        public Builder cardId(String cardId) {
            this.cardId = cardId;
            return this;
        }

        /**
         * Setter for cardLastDigits.
         * @param  cardLastDigits  String value for cardLastDigits.
         * @return Builder
         */
        public Builder cardLastDigits(String cardLastDigits) {
            this.cardLastDigits = cardLastDigits;
            return this;
        }

        /**
         * Builds a new {@link FinaliseFuelingRequestPayment} object using the set fields.
         * @return {@link FinaliseFuelingRequestPayment}
         */
        public FinaliseFuelingRequestPayment build() {
            return new FinaliseFuelingRequestPayment(method, cardId, cardLastDigits);
        }
    }
}
