/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for FinaliseFuelingRequestProductsItems type.
 */
public class FinaliseFuelingRequestProductsItems {
    private String productId;
    private String productName;
    private Double unitPrice;

    /**
     * Default constructor.
     */
    public FinaliseFuelingRequestProductsItems() {
    }

    /**
     * Initialization constructor.
     * @param  productId  String value for productId.
     * @param  productName  String value for productName.
     * @param  unitPrice  Double value for unitPrice.
     */
    public FinaliseFuelingRequestProductsItems(
            String productId,
            String productName,
            Double unitPrice) {
        this.productId = productId;
        this.productName = productName;
        this.unitPrice = unitPrice;
    }

    /**
     * Getter for ProductId.
     * @return Returns the String
     */
    @JsonGetter("productId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductId() {
        return productId;
    }

    /**
     * Setter for ProductId.
     * @param productId Value for String
     */
    @JsonSetter("productId")
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * Getter for ProductName.
     * @return Returns the String
     */
    @JsonGetter("productName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductName() {
        return productName;
    }

    /**
     * Setter for ProductName.
     * @param productName Value for String
     */
    @JsonSetter("productName")
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Getter for UnitPrice.
     * @return Returns the Double
     */
    @JsonGetter("unitPrice")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getUnitPrice() {
        return unitPrice;
    }

    /**
     * Setter for UnitPrice.
     * @param unitPrice Value for Double
     */
    @JsonSetter("unitPrice")
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * Converts this FinaliseFuelingRequestProductsItems into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FinaliseFuelingRequestProductsItems [" + "productId=" + productId + ", productName="
                + productName + ", unitPrice=" + unitPrice + "]";
    }

    /**
     * Builds a new {@link FinaliseFuelingRequestProductsItems.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FinaliseFuelingRequestProductsItems.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .productId(getProductId())
                .productName(getProductName())
                .unitPrice(getUnitPrice());
        return builder;
    }

    /**
     * Class to build instances of {@link FinaliseFuelingRequestProductsItems}.
     */
    public static class Builder {
        private String productId;
        private String productName;
        private Double unitPrice;



        /**
         * Setter for productId.
         * @param  productId  String value for productId.
         * @return Builder
         */
        public Builder productId(String productId) {
            this.productId = productId;
            return this;
        }

        /**
         * Setter for productName.
         * @param  productName  String value for productName.
         * @return Builder
         */
        public Builder productName(String productName) {
            this.productName = productName;
            return this;
        }

        /**
         * Setter for unitPrice.
         * @param  unitPrice  Double value for unitPrice.
         * @return Builder
         */
        public Builder unitPrice(Double unitPrice) {
            this.unitPrice = unitPrice;
            return this;
        }

        /**
         * Builds a new {@link FinaliseFuelingRequestProductsItems} object using the set fields.
         * @return {@link FinaliseFuelingRequestProductsItems}
         */
        public FinaliseFuelingRequestProductsItems build() {
            return new FinaliseFuelingRequestProductsItems(productId, productName, unitPrice);
        }
    }
}
