/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import com.shell.apitest.ApiHelper;
import com.shell.apitest.ShellEVClient;
import com.shell.apitest.exceptions.ApiException;
import com.shell.apitest.models.CancelFuelingRequest;
import com.shell.apitest.models.FinaliseFuelingRequest;
import io.apimatic.core.utilities.TestHelper;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class PartnerNotificationControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static ShellEVClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static PartnerNotificationController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getPartnerNotificationController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * To access the Partner’s endpoints, for sending callback messages, Shell will need to connect
     * to the Partner API end points. It is recemmended that the partner offers OAuth 2.0 as a
     * standard for call back APIs and will require the OAuth 2.0 token for authentication. Note
     * this needs to be implemented over HTTPS.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestPartnerToken() throws Exception {
        // Parameters for the API call
        String grantType = 
                "client_credentials";
        String clientId = 
                "SOFflRakNlwnWlxfOXQ4GHDVyqGawuKA";
        String clientSecret = 
                "cRnWgw7gACqM3gVS";

        // Set callback and perform API call
        try {
            controller.partnerToken(grantType, clientId, clientSecret);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

    /**
     * Enables Shell to inform partner of the successful completion of a transaction. Note this
     * needs to be implemented over HTTPS.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestFinaliseFueling() throws Exception {
        // Parameters for the API call
        FinaliseFuelingRequest body = null;

        // Set callback and perform API call
        try {
            controller.finaliseFueling(body);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Enables Shell to inform partner that a Mobile Payment transaction has been cancelled by Shell
     * as an error/issue occured. Note this needs to be implemented over HTTPS.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestCancelFueling() throws Exception {
        // Parameters for the API call
        CancelFuelingRequest body = null;

        // Set callback and perform API call
        try {
            controller.cancelFueling(body);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
