/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for MppAccesTokenErrorResponseException type.
 */
public class MppAccesTokenErrorResponseException extends ApiException {
    private static final long serialVersionUID = 8654717287224727290L;
    private String error;
    private String errorCode;
    private String errorDescription;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public MppAccesTokenErrorResponseException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * error code or short description
     * @return Returns the String
     */
    @JsonGetter("error")
    public String getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * error code or short description
     * @param error Value for String
     */
    @JsonSetter("error")
    private void setError(String error) {
        this.error = error;
    }

    /**
     * Getter for ErrorCode.
     * error code or short description due to invalid request or invalid client ID
     * @return Returns the String
     */
    @JsonGetter("error_code")
    public String getErrorCode() {
        return this.errorCode;
    }

    /**
     * Setter for ErrorCode.
     * error code or short description due to invalid request or invalid client ID
     * @param errorCode Value for String
     */
    @JsonSetter("error_code")
    private void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * Getter for ErrorDescription.
     * Description of the error
     * @return Returns the String
     */
    @JsonGetter("error_description")
    public String getErrorDescription() {
        return this.errorDescription;
    }

    /**
     * Setter for ErrorDescription.
     * Description of the error
     * @param errorDescription Value for String
     */
    @JsonSetter("error_description")
    private void setErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
    }
}
