/*
 * ShellSmartPayAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for PaymentEnablementErrorResponseException type.
 */
public class PaymentEnablementErrorResponseException extends ApiException {
    private static final long serialVersionUID = 2796938243189726477L;
    private Integer code;
    private String message;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public PaymentEnablementErrorResponseException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Code.
     * @return Returns the Integer
     */
    @JsonGetter("code")
    public Integer getCode() {
        return this.code;
    }

    /**
     * Setter for Code.
     * @param code Value for Integer
     */
    @JsonSetter("code")
    private void setCode(Integer code) {
        this.code = code;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("message")
    public String getMessageField() {
        return this.message;
    }

    /**
     * Setter for Message.
     * @param messageField Value for String
     */
    @JsonSetter("message")
    private void setMessageField(String messageField) {
        this.message = messageField;
    }

    /**
     * Converts this PaymentEnablementErrorResponseException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PaymentEnablementErrorResponseException [" + "statusCode=" + getResponseCode()
                + ", message=" + getMessage() + ", code=" + code + ", message=" + message + "]";
    }
}
